Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 3
Rules claiming more threads will be scaled down.
Select jobs to execute...

[Tue Nov  2 13:45:06 2021]
rule splitting_group_by_individual:
    input: data/cases_controls/cases_controls_rds_format/all_samples_normalized_CONTROLS.rds
    output: data/20_80_splits_group_by_ind/20_all_samples_normalized_CONTROLS_TEST.rds, data/20_80_splits_group_by_ind/80_all_samples_normalized_CONTROLS_TEST.rds
    log: logs/processed_notebooks/processed_Data_splitting_20_80_group_by_individual_CONTROLS.r.ipynb
    jobid: 0
    wildcards: input_suffix=CONTROLS
    threads: 3
    resources: mem_mb=100000, disk_mb=6325, tmpdir=/scratch/56735110, time=12:00:00

jupyter-nbconvert --log-level ERROR --execute --output /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/logs/processed_notebooks/processed_Data_splitting_20_80_group_by_individual_CONTROLS.r.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/scripts/tmpc6v9s5ll.Data_splitting_20_80_group_by_individual.r.ipynb
Activating conda environment: /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187
Traceback (most recent call last):
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/bin/jupyter-nbconvert", line 7, in <module>
    from nbconvert.nbconvertapp import main
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 141, in <module>
    class NbConvertApp(JupyterApp):
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/nbconvertapp.py", line 226, in NbConvertApp
    """.format(formats=get_export_names()))
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 146, in get_export_names
    e = get_exporter(exporter_name)(config=config)
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/exporters/base.py", line 103, in get_exporter
    if getattr(exporter(config=config), 'enabled', True):
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 330, in __init__
    super().__init__(config=config, **kw)
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
    self._init_preprocessors()
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 497, in _init_preprocessors
    conf = self._get_conf()
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/site-packages/nbconvert/exporters/templateexporter.py", line 517, in _get_conf
    if conf_path.exists():
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/pathlib.py", line 1414, in exists
    self.stat()
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/lib/python3.9/pathlib.py", line 1222, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187/share/jupyter/nbconvert/templates/html/conf.json'
[Tue Nov  2 13:45:08 2021]
Error in rule splitting_group_by_individual:
    jobid: 0
    output: data/20_80_splits_group_by_ind/20_all_samples_normalized_CONTROLS_TEST.rds, data/20_80_splits_group_by_ind/80_all_samples_normalized_CONTROLS_TEST.rds
    log: logs/processed_notebooks/processed_Data_splitting_20_80_group_by_individual_CONTROLS.r.ipynb (check log file(s) for error message)
    conda-env: /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187

Traceback (most recent call last):
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 593, in _callback
    raise ex
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 579, in cached_or_run
    run_func(*args)
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2460, in run_wrapper
    raise ex
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2441, in run_wrapper
    runtime_sourcecache_path,
  File "/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/snakefile_Anika_test", line 46, in __rule_splitting_group_by_individual
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/notebook.py", line 295, in notebook
    executor.evaluate(edit=edit)
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/script.py", line 381, in evaluate
    self.execute_script(fd.name, edit=edit)
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/notebook.py", line 92, in execute_script
    self._execute_cmd(cmd, fname_out=fname_out, fname=fname)
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/script.py", line 425, in _execute_cmd
    **kwargs
  File "/home/anikago/miniconda3/envs/ctDNA/lib/python3.7/site-packages/snakemake/shell.py", line 265, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'source /home/anikago/miniconda3/bin/activate '/faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/conda/1cc9c1aecfca2e5f4a23e8b12a534187'; set -euo pipefail;  jupyter-nbconvert --log-level ERROR --execute --output /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/logs/processed_notebooks/processed_Data_splitting_20_80_group_by_individual_CONTROLS.r.ipynb --to notebook --ExecutePreprocessor.timeout=-1 /faststorage/project/DELFI1/Workspaces/CarmenAndAnika/.snakemake/scripts/tmpc6v9s5ll.Data_splitting_20_80_group_by_individual.r.ipynb' returned non-zero exit status 1.
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
